name: Code Quality Scan

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: read
  security-events: write

jobs:
  docker:
    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: rust

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Run Clippy
        run: cargo clippy --all-targets --all-features

      - name: Build
        run: cargo build --workspace --all-features
      
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

      - name: Cleanup
        if: always()
        run: |
          docker stop ci-cd-playground || true
          docker rm ci-cd-playground || true

