name: Build Docker Image

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write
  security-events: write

jobs:
  docker:

    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:latest .
      
      - name: Generate Trivy Report
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: ghcr.io/${{ github.repository }}:latest
          format: sarif
          output: trivy-results.sarif
          exit-code: 0
          ignore-unfixed: false
          vuln-type: os,library
          severity: UNKNOWN,LOW,MEDIUM,CRITICAL,HIGH

      - name: Upload sarif report
        if: always()
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: trivy-results.sarif

      - name: Docker Image Scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: ghcr.io/%{{ github.repository }}:latest
          format: table
          exit-code: 1
          ignore-unfixed: true
          vuln-type: os,library
          severity: HIGH,CRITICAL

      - name: Push image
        run: |
          docker push ghcr.io/${{ github.repository }}:latest