name: Build Docker Image

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  security-events: write

jobs:
  docker:

    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Run Clippy
        run: cargo clippy --all-targets --all-features

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:latest .
      
      - name: Generate Trivy Report
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: ghcr.io/${{ github.repository }}:latest
          format: sarif
          output: trivy-results.sarif
          exit-code: 0
          ignore-unfixed: true
          vuln-type: os,library
          severity: UNKNOWN,LOW,MEDIUM,CRITICAL,HIGH

      - name: Upload sarif report
        if: always()
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: trivy-results.sarif

      - name: Docker Image Scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: ghcr.io/${{ github.repository }}:latest
          format: table
          exit-code: 1
          ignore-unfixed: true
          vuln-type: os,library
          severity: HIGH,CRITICAL

      - name: Run Container
        run: |
          docker run -d \
            --name ci-cd-playground \
            -p 8080:8080 \
            ghcr.io/${{ github.repository }}:latest

      - name: Wait for app
        run: |
          timeout 60 bash -c '
            until curl -fs http://localhost:8080; do
              sleep 2
            done
            '

      - name: OWASP ZAP Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: 'http://localhost:8080'
          allow_issue_writing: false

      - name: Upload ZAP Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: report_html.html

      - name: Push image
        run: |
          docker push ghcr.io/${{ github.repository }}:latest